CREATE TABLE IF NOT EXISTS user_section_orders (
    id BIGSERIAL PRIMARY KEY,
    group_id VARCHAR(255) NOT NULL,
    section_id BIGINT NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL,
    position_order INTEGER,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT
);
